[custom]
# 本地网络
surge_ruleset=🎯 国内网络,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Lan/Lan.list

# 去广告
; surge_ruleset=🛡️ 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
; surge_ruleset=🛡️ 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list

# AI
surge_ruleset=☁️ OpenAI,https://raw.githubusercontent.com/7revor/proxy-rules/main/ai.list
# proxy
surge_ruleset=🚀 科学上网,https://raw.githubusercontent.com/7revor/proxy-rules/main/proxy.list

# 直连
surge_ruleset=🎯 国内网络,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Direct/Direct.list
# steam 登录地址（直连登录后下载会分配国内cdn地址）
surge_ruleset=🎯 国内网络,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/SteamCN/SteamCN.list
# psn 直连
surge_ruleset=🎯 国内网络,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/PlayStation/PlayStation.list
# game download
surge_ruleset=🎯 国内网络,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Game/GameDownloadCN/GameDownloadCN.list

# telegram
surge_ruleset=🚀 科学上网,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Telegram/Telegram.list
# Developer
surge_ruleset=🚀 科学上网,https://raw.githubusercontent.com/zydou/domain-list-community-converter/surge-rule-set/category-dev.txt

surge_ruleset=🚀 科学上网,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/YouTube/YouTube.list
surge_ruleset=🚀 科学上网,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Netflix/Netflix.list

# Google
surge_ruleset=🚀 科学上网,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Google/Google.list
# Microsoft
surge_ruleset=🖥️ 微软服务,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Microsoft/Microsoft.list
# GFW
surge_ruleset=🚀 科学上网,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Proxy/Proxy_All_No_Resolve.list
# China
surge_ruleset=🎯 国内网络,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/China/China_All_No_Resolve.list
# geo ip（resolve）
surge_ruleset=🎯 国内网络,[]GEOIP,CN

# TEMPLATE
{% if request.target == "clash" %}
surge_ruleset=🎯 国内网络,[]DST-PORT,22
{% endif %}

# final
surge_ruleset=🐟 其他网站,[]FINAL

# 分组
custom_proxy_group=🚀 科学上网`select`(.*)
custom_proxy_group=☁️ OpenAI`select`(.*)
custom_proxy_group=🖥️ 微软服务`select`[]DIRECT`(.*)
custom_proxy_group=🎯 国内网络`select`[]DIRECT`(.*)
custom_proxy_group=🐟 其他网站`select`(.*)`[]DIRECT

enable_rule_generator=true
overwrite_original_rules=true
